### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Varun23102002** [srodrigo23/mediaboxplayer#1]
Looking for app to stream files in Dropbox

**Comment by srodrigo23** [comment]
Thank you for your interest!... Well, you only have to login to your Dropbox account and give the permission for access for your content. You can stream only media files.

**Comment by Varun23102002** [comment]
I know but how I get .apk file

**Comment by srodrigo23** [comment]
Share me your mail and I'll share the apk.

**Comment by Varun23102002** [comment]
varunbh307@gmail.com

**Comment by Varun23102002** [comment]
Bro please send me when you receive message - varunbh307@gmail.com

**Comment by srodrigo23** [comment]
use this [link](https://www.dropbox.com/scl/fi/ottkpga99ln2mop3tygw0/mediaboxplayer.apk?rlkey=agiab2wx04v62pe4mn0op2tki&st=4kaaltzh&dl=0), please tell me if you can download it!
